# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharespace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='space',
            name='space_type',
            field=models.CharField(default='home', max_length=10),
            preserve_default=False,
        ),
    ]
