# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharespace', '0004_auto_20160131_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('THEATER', '소극장'), ('METTINGROOM', '회의실'), ('PARKING', '주차장')], default='THEATER', max_length=10),
        ),
    ]
